# Generated by Django 3.1.12 on 2022-04-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='title',
            field=models.CharField(default=models.CharField(max_length=100), max_length=50),
        ),
    ]
