# Generated by Django 4.0.4 on 2022-05-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_password_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=100)),
                ('title', models.CharField(default=models.CharField(max_length=100), max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('managed_password', models.CharField(max_length=75)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
