# Generated by Django 4.1.2 on 2022-10-30 16:21

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_managedpassword_delete_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedpassword',
            name='managed_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=75)),
        ),
    ]
